apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qxbiz4loj-java-quarkus 
  janus-idp.io/tekton: qxbiz4loj-java-quarkus
  backstage.io/kubernetes-id: qxbiz4loj-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qxbiz4loj-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml